# 🧬 FUNDING PROTOCOL: Project Human-Patch v1.0
# We are open to Research Grants & Institutional Collaboration.

github: # Agar future me GitHub Sponsors bana to yahan user ID dalenge
patreon: # Abhi hume chote donations nahi chahiye
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 


custom: ["sy1174304@gmail.com "]
